server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.server: DEBUG

spring:
  
  datasource:
    url: jdbc:mysql://localhost:3306/backoffice?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false