server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.server: DEBUG

spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-server.test:9000
        client:
          articles-client:
            registration:
              client-id: articles-client
              client-secret: "{noop}secret"
              client-name: Articles Client
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://127.0.0.1:8080/login/oauth2/code/articles-client-oidc
                - http://127.0.0.1:8080/authorized
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - openid
                - articles.read
            require-authorization-consent: true
  datasource:
    url: jdbc:mysql://localhost:3306/backoffice?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false